### ISSUE TITLE
browserify

### ISSUE THREAD

**Issue by boneskull** [theKashey/rewiremock#113] opened 2020-05-11 18:53 UTC
there's some stuff in the works to move Mocha way from browserify and onto webpack, but not sure when that'll land.

in the meantime, I'm struggling to get rewiremock working in a browserify bundle via karma.  it's throwing an exception because `require.resolve` does not exist.  first, it throws because of the `node-libs-browser` module:

```
  Uncaught TypeError: require.resolve is not a function
  at /var/folders/74/theKashey/rewiremock/node_modules/node-libs-browser/index.js:1:1 <- /var/folders/74/p0gxrmy93fq88nm66cs7z42h0000gn/T/55824eb469904ee97753db535d0bc15b.browserify.js:46563:31
```

Even if that's addressed somehow, it will certainly throw in the two other places that use `require.resolve` in the codebase (`nested.js` & `mockModule.js`).

For this to work, I'm going to guess you'd want to publish a browser bundle and reference it in the `browser` field of `package.json`--or otherwise point to a non-bundled, browser-specific implementation.  But that's just my guess.

But... this may be a "WONTFIX" for you--and I get it.  Just something I ran into and thought it wouldn't hurt to mention.

**Comment by boneskull** [comment] 2020-05-11 18:55
(Browserify itself will replace references to `require.resolve` with its own [resolve](https://npm.im/resolve) module, but it is nontrivial to try to create a browserify bundle for a dependency)

**Comment by theKashey** [comment] 2020-05-11 23:05
- `node-libs-browser` is used only for webpack (however should be used for mocha case as well), but as long as all the stuff imported statically - it's causing issues for mocha. I am not sure which approach is better here.

- `require.resolve` is not a problem. It's better to call them "leftovers" - in both cases it's used to self-wipe - `delete require.cache[require.resolve(__filename)];`, and there is a better function for it.

**Comment by theKashey** [comment] 2020-05-12 03:31
@boneskull - please try that branch.

**Comment by boneskull** [comment] 2020-05-19 22:21
I get

```
Uncaught Error: Rewiremock: there is no "parent module". Is there two HotModuleReplacementPlugins?
```

**Comment by boneskull** [comment] 2020-05-19 22:23
It'd also (theoretically) work if there was a "globals" bundle of rewiremock available.  Then I could make it work in Karma by throwing it in a `<script>` tag, and browserify wouldn't need to know about it.

**Comment by boneskull** [comment] 2020-05-19 22:24
(That branch works when running in node, just not in karma/karma-browserify)

**Comment by theKashey** [comment] 2020-05-19 22:45
> Uncaught Error: Rewiremock: there is no "parent module"

Sounds like a problem with browserify module system, if it even exists.

So:
- https://github.com/browserify/browserify/pull/323 - support for parent, merged in 2013
- https://github.com/browserify/browserify/issues/976 - according to this one `yes --bare already does that!`, year 2014
- https://github.com/browserify/browserify/issues/41 - `socket.io` needed module.parent and there is none (year 2015, where did it go?), but decided to change their code. The outcome of the issue is not clear.

**Comment by theKashey** [comment] 2020-05-19 23:03
Look like there is no implementation of a real module system, as long as it's not really needed in "runtime".
Is it possible for you not to use browserify, but use webpack? 99% of the functionality works there.

**Comment by boneskull** [comment] 2020-05-20 18:54
K, thanks for looking in to this.  I think Mocha is moving to webpack anyway.  not sure if you meant to leave this open.

**Comment by boneskull** [comment] 2020-05-20 21:41
I was wrong; we're not going to use webpack--looks like we're going to use rollup instead.  This doesn't mean we're going to adopt ESM modules, though, given the current set of challenges there.

**Comment by theKashey** [comment] 2020-05-21 03:28
rollup's module system is a unknown for me yet. Haven't tried it, but reckon it should not be a problem. 
> However it should not work out of the box.

Probably it's time to __close this issue with WONT FIX__, and open a new one for rollup.

**Closed** 2020-05-21 03:29 UTC
